import type { Category, Product, Ad, Testimonial } from './types';

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'cat_thobes',
    name: 'ثياب يمنية وخليجية',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    order: 0,
  },
  {
    id: 'cat_suits',
    name: 'كوت وبدل رسمية',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
    order: 1,
  },
  {
    id: 'cat_vests',
    name: 'صديريات وأحزمة تراثية',
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
    order: 2,
  },
  {
    id: 'cat_shawls',
    name: 'شيلان ومقاطب كشميري',
    image: 'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?auto=format&fit=crop&w=800&q=80',
    order: 3,
  },
  {
    id: 'cat_fabrics',
    name: 'أقمشة تفصيل VIP',
    image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80',
    order: 4,
  },
  {
    id: 'cat_occasions',
    name: 'جلابيات وثياب سهرة',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
    order: 5,
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod_sanaani_royal',
    name: 'ثوب صنعاني ملكي مطرز يدوي',
    price: 38000,
    oldPrice: 45000,
    categoryId: 'cat_thobes',
    description:
      'ثوب يمني أصيل بتفصيل صنعاني متقن، مطرز يدوياً بخيوط البريسم الأصلية على الياقة والجيب والأكمام مع قماش قطني ياباني ناصع البياض.',
    color: 'أبيض لؤلؤي',
    colorHex: '#f8fafc',
    fabric: 'قطن تويوبو ياباني نخب أول',
    sizes: ['52', '54', '56', '58', '60', 'تفصيل خاص بالمقاس'],
    details: 'خياطة يدوية دقيقة، ياقة ملكية بارتفاع 4 سم، أزرار صدفية مخفية مقاومة للحرارة، جيب سري داخلي، كبك أكمام مزدوج.',
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: true,
    badge: 'best',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: 'prod_groom_blazer',
    name: 'كوت عريس رسمي كلاسيك صوف إنجليزي',
    price: 65000,
    oldPrice: 78000,
    categoryId: 'cat_suits',
    description:
      'كوت وبدلة عريس مفصلة على الباترون الإيطالي العصري، مصنوعة من صوف إنجليزي فاخر مقاوم للتجعد ومبطن بحرير ناعم.',
    color: 'كحلي ملكي داكن',
    colorHex: '#1e293b',
    fabric: 'صوف إنجليزي فائق النعومة 130s',
    sizes: ['48', '50', '52', '54', '56', 'تفصيل خاص بالمقاس'],
    details: 'أكتاف مهيكلة بدقة إيطالية، طيات صدر كلاسيكية، جيب للمنديل وجيب داخلي للساعة، خياطة يدوية للفتحات وأزرار قرن طبيعية.',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1612444530582-fc66183b16f7?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: true,
    badge: 'excl',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: 'prod_cashmere_shawl',
    name: 'شال كشميري ترمة نقشة ملكية فاخرة',
    price: 42000,
    oldPrice: 50000,
    categoryId: 'cat_shawls',
    description:
      'شال صوف كشميري أصلي بنقشة الترمة اليمنية التراثية المنسوجة يدوياً، ملمس دافئ وخفيف الوزن يمنحك هيبة وأناقة متكاملة.',
    color: 'بيج عسلي مطعم بعنابي',
    colorHex: '#d97706',
    fabric: 'صوف باشمينا كشميري 100%',
    sizes: ['مقاس موحد 58 إنش'],
    details: 'نقشة لوزية ملكية دقيقة، أطراف مبرومة يدوياً، ألوان ثابتة زاهية تم نسجها بخيوط طبيعية.',
    images: [
      'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: true,
    badge: 'best',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: 'prod_gold_vest',
    name: 'صديرية يمنية مطرزة بالقصب والذهب',
    price: 26000,
    oldPrice: 32000,
    categoryId: 'cat_vests',
    description:
      'صديرية تراثية أنيقة صُممت خصيصاً للمناسبات والأعراس، مطرزة بخيوط القصب الذهبي اللامع فوق قماش مخمل أسود فاحم.',
    color: 'أسود مع تطريز ذهبي',
    colorHex: '#0f172a',
    fabric: 'مخمل كوري فاخر مع قصب ذهبي',
    sizes: ['M', 'L', 'XL', 'XXL', 'تفصيل خاص بالمقاس'],
    details: 'قصة صدر كلاسيكية مريحة، حزام جانبي خلفي لضبط المقاس، مبطنة بالكامل بحرير أسود ناعم.',
    images: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: false,
    badge: 'new',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: 'prod_linen_thobe',
    name: 'ثوب كتان ياباني كاجوال VIP بارد',
    price: 29000,
    oldPrice: 34000,
    categoryId: 'cat_thobes',
    description:
      'ثوب عصري مريح من قماش الكتان الطبيعي المعالج المقاوم للتجعد، مناسب جداً للدوام والاستخدام اليومي الصيفي.',
    color: 'رمادي جليدي هادئ',
    colorHex: '#94a3b8',
    fabric: 'كتان ياباني بارد 100%',
    sizes: ['52', '54', '56', '58', '60'],
    details: 'ياقة قلابي مفتوحة عصرية، قماش يسمح بالتنفس وانسيابي، تشطيب داخلي بأعلى معايير الخياطة الفاخرة.',
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: true,
    badge: 'new',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: 'prod_bespoke_suit',
    name: 'بدلة رجالية تفصيل إيطالي فحمية',
    price: 72000,
    oldPrice: 85000,
    categoryId: 'cat_suits',
    description:
      'طقم بدلة رسمية قطعتين (جاكيت وبنطلون) بتفصيل شخصي مخصص على مقاساتك بدقة متناهية، مخصصة لرجال الأعمال والمناسبات الراقية.',
    color: 'رمادي فحمي كلاسيكي',
    colorHex: '#334155',
    fabric: 'صوف وموهير إيطالي فائق الجودة',
    sizes: ['48', '50', '52', '54', '56', 'تفصيل خاص بالمقاس'],
    details: 'طيات صدر واسعة أنيقة، خياطة حواف بيك ستيتش يدوية، بنطلون بقصة مريحة مع حزام قابل للتعديل.',
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: true,
    badge: 'excl',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'prod_toyobo_fabric',
    name: 'طاقة قماش تويوبو ياباني ملكي أصلي',
    price: 35000,
    categoryId: 'cat_fabrics',
    description:
      'قماش ياباني نخب ممتاز ناصع البياض وقليل التجعد، يتميز بنعومة فائقة وثبات رائع على الجسم مع لمعة طبيعية هادئة.',
    color: 'أبيض ساطع / أبيض طبيعي',
    colorHex: '#ffffff',
    fabric: 'تويوبو ياباني 100% مختوم بالعلامة الأصلية',
    sizes: ['طاقة كاملة (25 ياردة تكفي 7 ثياب)', 'تفصيل ثوب مفرد (3.5 متر)'],
    details: 'مقاوم للاصفرار مع الغسيل المتكرر، ملمس حريري ناعم، وزن وسطي مناسب لجميع فصول السنة.',
    images: [
      'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: false,
    badge: 'best',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
  },
  {
    id: 'prod_yemeni_jalabiya',
    name: 'جلابية وسهرة يمنية مطرزة بفصوص فاخرة',
    price: 48000,
    oldPrice: 56000,
    categoryId: 'cat_occasions',
    description:
      'جلابية راقية بتفصيل يمني حريري، مشغولة بتطريزات فلكلورية دقيقة مع فصوص براقة متناسقة، تجمع بين التراث الأصيل ورونق الموضة.',
    color: 'زمردي مع ذهبي',
    colorHex: '#065f46',
    fabric: 'حرير كريب شيفون فاخر مطعم بالزري',
    sizes: ['S', 'M', 'L', 'XL', 'تفصيل خاص بالمقاس'],
    details: 'أكمام كلوش واسعة، تطريز يدوي على الصدر والظهر والأطراف، بطانة داخلية ناعمة وساترة.',
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: true,
    badge: 'new',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: 'prod_traditional_maqtab',
    name: 'طقم مقطب يمني قطني مع حزام وشال متناسق',
    price: 19500,
    oldPrice: 24000,
    categoryId: 'cat_shawls',
    description:
      'مقطب أصيل منتقى من أجود خيوط القطن المغزول بنقشة تراثية كلاسيكية مريحة، مع حزام مطرز متناسق للمناسبات.',
    color: 'عنابي مع خطوط كحلية',
    colorHex: '#881337',
    fabric: 'قطن يمني مغزول 100%',
    sizes: ['مقاس موحد حر'],
    details: 'أطراف مهدبة يدوياً، حزام مشدود بقوة مع حلقات تثبيت، ألوان زاهية ومريحة جداً في الحركة.',
    images: [
      'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: false,
    badge: 'best',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
  {
    id: 'prod_omani_classic',
    name: 'ثوب خليجي كلاسيك تطريز خيط بريسم خفيف',
    price: 31000,
    oldPrice: 36000,
    categoryId: 'cat_thobes',
    description:
      'ثوب خليجي انسيابي بقصة مريحة وطربوشة أنيقة، تطريز يدوي دقيق بخيط البريسم، مثالي للمناسبات الرسمية والأعياد.',
    color: 'سكري هادئ (Off-White)',
    colorHex: '#fef3c7',
    fabric: 'قماش سلك كوري كريب فاخر',
    sizes: ['52', '54', '56', '58', '60', 'تفصيل خاص بالمقاس'],
    details: 'خياطة أزرار يدوية، كبك مزدوج، قماش خفيف مقاوم للتجعد يمنح إحساساً بالانتعاش طوال اليوم.',
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: true,
    badge: 'new',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
  },
  {
    id: 'prod_wedding_bisht',
    name: 'بشت ملكي فاخر زري ألماني أصلي مذهب للأعراس',
    price: 68000,
    oldPrice: 80000,
    categoryId: 'cat_occasions',
    description:
      'بشت ملكي للأعراس والمناسبات الكبرى، مشغول يدوياً بخيوط الزري الألماني المذهب عيار أصلي، قماش صوف نجفي ناعم خفيف يمنح وقاراً وهيبة استثنائية.',
    color: 'أسود ملكي مع تطريز ذهبي',
    colorHex: '#18181b',
    fabric: 'صوف نجفي ناعم خيوط زري ألماني',
    sizes: ['27', '28', '29', '30', 'تفصيل خاص بالمقاس'],
    details: 'دربوية ملكية عريضة، قيطان يدوي متين، خيوط ذهبية مقاومة لتغير اللون، كركوشة حريرية مجدولة يدوياً.',
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: true,
    badge: 'excl',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: 'prod_sanaani_vest_luxury',
    name: 'صديرية صنعانية ديباج ملكي مطرزة بقصب الفضة',
    price: 24000,
    oldPrice: 28000,
    categoryId: 'cat_vests',
    description:
      'صديرية يمنية صنعانية تراثية من الديباج الدمشقي الفاخر، محاكة يدوياً بتطريز قصب الفضة على الأطراف والياقة لتنسيقها مع الجنبية والشال.',
    color: 'زيتي كحلي مع فضي',
    colorHex: '#1e3a8a',
    fabric: 'ديباج فاخر مبطن بحرير ياباني',
    sizes: ['S', 'M', 'L', 'XL', 'XXL', 'تفصيل خاص بالمقاس'],
    details: 'جيوب جانبية للجنبية والساعة، أزرار قصبية يدوية، تبطين داخلي بارد مريح للأجواء الحارة والمعتدلة.',
    images: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: true,
    badge: 'best',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 11).toISOString(),
  },
  {
    id: 'prod_english_suit_coat',
    name: 'كوت صوف إنجليزي فحم كاروهات VIP',
    price: 49000,
    oldPrice: 58000,
    categoryId: 'cat_suits',
    description:
      'كوت بدلة رجالي فخم بتفصيل دقيق وقصة إيطالية حديثة، منسوج من صوف إنجليزي فائق النعومة، مثالي لاجتماعات العمل والمناسبات الرسمية.',
    color: 'رمادي فحمي كاروهات ناعم',
    colorHex: '#374151',
    fabric: 'صوف إنجليزي سوبر 140',
    sizes: ['48', '50', '52', '54', '56', 'تفصيل خاص بالمقاس'],
    details: 'ياقة شال عصرية، فتحتين خلفيتين، أزرار عاج طبيعية، جيوب داخلية مخصصة للأقلام والهاتف.',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: true,
    badge: 'best',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
  },
  {
    id: 'prod_habr_shawl_original',
    name: 'شال يمني حبرة صعدي يدوي أصلي نخب أول',
    price: 36000,
    oldPrice: 42000,
    categoryId: 'cat_shawls',
    description:
      'شال صعدي حبرة منسوج بأنوال يدوية تقليدية، ألوان تراثية غنية وثابتة، نقشات يمنية أصيلة تعكس عراقة الزي اليمني.',
    color: 'خمري وبيج ونبيتي',
    colorHex: '#7f1d1d',
    fabric: 'صوف طبيعي نقي 100% مغزول يدوياً',
    sizes: ['مقاس رسمي 2.5 * 1.2 متر'],
    details: 'شراشيب معقودة باليد حبة بحبة، نسيج شتوي دافئ وخفيف الوزن على الكتف، ثبات عالي للألوان.',
    images: [
      'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: false,
    badge: 'new',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 13).toISOString(),
  },
  {
    id: 'prod_japanese_silk_thobe',
    name: 'ثوب أميري قماش شيكيبو ياباني بارد مقاوم للتجعد',
    price: 35000,
    oldPrice: 40000,
    categoryId: 'cat_thobes',
    description:
      'ثوب فائق الأناقة بقماش شيكيبو ياباني طبيعي مسامي، يتميز بالبرودة والانسيابية ومقاومة التجعد وسهولة الكي.',
    color: 'أبيض ثلجي',
    colorHex: '#ffffff',
    fabric: 'قماش شيكيبو Shikibo قطن معالج',
    sizes: ['52', '54', '56', '58', '60', 'تفصيل خاص بالمقاس'],
    details: 'ياقة قلاب كلاسيكية، جيب قلم مع جيب جوال عميق، خياطة مخفية دقيقة بتقنية الدرزة المزدوجة.',
    images: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: true,
    badge: 'best',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
  },
  {
    id: 'prod_yemeni_jalabiya_luxe',
    name: 'جلابية مجالس يمنية قطن مرسيليا مطرزة',
    price: 29000,
    oldPrice: 34000,
    categoryId: 'cat_occasions',
    description:
      'جلابية رجالية مريحة للمجالس والمناسبات العائلية والأعياد، بقماش قطن مرسيليا الناعم وتطريز صنعاني مميز على الصدر.',
    color: 'رصاصي فضي هادئ',
    colorHex: '#9ca3af',
    fabric: 'قطن مرسيليا قطيفة ناعم',
    sizes: ['52', '54', '56', '58', '60', 'تفصيل خاص بالمقاس'],
    details: 'أكمام واسعة مريحة، ياقة مفتوحة بزر واحد مخفي، قصة فضفاضة توفر أقصى درجات الراحة.',
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=320&q=55',
    published: true,
    stock: true,
    featured: false,
    badge: 'new',
    views: 0,
    waClicks: 0,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  },
];

export const DEMO_ADS: Ad[] = [
  {
    id: 'ad_wedding_discount',
    text: 'عروض موسم الأعراس: خصم 15% على تفصيل بدل وكوت العرسان مع ثوب إضافي هدية',
    icon: 'fa-solid fa-crown',
    kind: 'gold',
    linkType: 'cat',
    linkValue: 'cat_suits',
    active: true,
  },
  {
    id: 'ad_home_tailoring',
    text: 'خدمة التوصيل وأخذ المقاسات في المنزل متوفرة لجميع عملائنا الكرام داخل العاصمة',
    icon: 'fa-solid fa-tape',
    kind: 'green',
    linkType: 'none',
    active: true,
  },
  {
    id: 'ad_cashmere_arrival',
    text: 'وصلت حديثاً: تشكيلة الشيلان الكشميري الترمة والأقمشة اليابانية الفاخرة لعام 2026',
    icon: 'fa-solid fa-sparkles',
    kind: 'dark',
    linkType: 'cat',
    linkValue: 'cat_shawls',
    active: true,
  },
];

export const DEMO_TESTIMONIALS: Testimonial[] = [
  {
    id: 'testi_1',
    name: 'المهندس عادل الحميري',
    stars: 5,
    text: 'أفضل محل تفصيل تعاملت معه في صنعاء بدون مبالغة. دقة متناهية في المقاسات والتزام بالموعد المحدد بدون أي تأخير. الثوب جلس كأنه مرسوم رسم.',
  },
  {
    id: 'testi_2',
    name: 'الأستاذ صادق العبسي',
    stars: 5,
    text: 'تفصيل الكوت والبدلة لحفل زفاف ابني كان أكثر من رائع، خامة الصوف وجودة الخياطة والتبطين الداخلي تضاهي أفخم الماركات العالمية.',
  },
  {
    id: 'testi_3',
    name: 'الدكتور نبيل الشامي',
    stars: 5,
    text: 'شريت منهم شال كشميري وثوبين للعيد، الجودة أصيلة والتطريز الصنعاني اليدوي متقن جداً. فخور بوجود براند يمني بهذا المستوى الرفيع.',
  },
  {
    id: 'testi_4',
    name: 'الأخ وليد القاسمي',
    stars: 5,
    text: 'التعامل راقي جداً وخدمة الواتساب سريعة ومحترمة. استلمت طلبي في الموعد والمقاسات كانت مطابقة 100%، شكراً براند اليمن.',
  },
];
